# Generated by Django 4.2.1 on 2023-06-18 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('contact', models.IntegerField(max_length=20)),
                ('location', models.CharField(max_length=25)),
                ('store_name', models.CharField(max_length=32)),
                ('password', models.IntegerField(max_length=32)),
                ('user_name', models.CharField(max_length=32)),
            ],
        ),
    ]
