# Generated by Django 4.2.1 on 2023-06-18 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='contact',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='owner',
            name='password',
            field=models.PositiveIntegerField(),
        ),
    ]
