# Generated by Django 4.2.3 on 2023-07-13 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('contact', models.PositiveIntegerField()),
                ('location', models.CharField(max_length=25)),
                ('store_name', models.CharField(max_length=32)),
                ('password', models.PositiveIntegerField()),
                ('user_name', models.CharField(max_length=32)),
            ],
        ),
    ]
