# Generated by Django 4.2.3 on 2023-07-13 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('shipment_date', models.DateTimeField()),
                ('shipment_status', models.CharField(max_length=200)),
                ('shipment_type', models.CharField(max_length=200)),
            ],
        ),
    ]
