# Generated by Django 4.2.3 on 2023-07-14 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_products_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='owner',
            new_name='userVendor',
        ),
    ]
