# Generated by Django 4.2.3 on 2023-07-14 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='inventory',
            field=models.ManyToManyField(to='inventory.products'),
        ),
    ]
