# Generated by Django 4.2.3 on 2023-07-13 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart', '0001_initial'),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_name', models.CharField(max_length=50, verbose_name='Name')),
                ('order_number', models.IntegerField(verbose_name='Order number')),
                ('order_total', models.FloatField(verbose_name='Order Total')),
                ('date', models.DateField(verbose_name='Date')),
                ('delivery_date', models.DateTimeField(verbose_name='')),
                ('cart', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cart.cart')),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
            ],
        ),
    ]
